#!/usr/bin/env bash
# Generate a self-contained HTML dashboard from the audit ledger.
#
# Usage: dashboard/generate.sh [db_path] [out_path]
# Default: dashboard/generate.sh workspace/.state/audit.sqlite dashboard/index.html
#
# No server required, no JS deps — open the resulting file in a browser.

set -euo pipefail

DB="${1:-workspace/.state/audit.sqlite}"
OUT="${2:-dashboard/index.html}"

if [ ! -f "$DB" ]; then
  echo "audit DB not found at $DB" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

now_utc="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
abs_db="$(readlink -f "$DB")"

# --- helpers ------------------------------------------------------------------

# Emit a section: <h2> heading + a table generated by sqlite3 -html.
# The query may emit sentinel tokens of the form %PILL:<class>:<label>% inside
# a cell; those are re-inflated to <span class="pill <class>"><label></span>
# after sqlite3 escapes the HTML. Sentinels never occur in real data.
section() {
  local title="$1" query="$2"
  echo "<section>"
  echo "<h2>$title</h2>"
  local html
  html="$(sqlite3 -html "$DB" "$query" 2>/dev/null || echo '')"
  if [ -z "$html" ]; then
    echo '<p class="empty">no rows</p>'
  else
    # sqlite3 -html emits raw <TR><TD>…, no <table>. Wrap it and rehydrate pills.
    printf '<table>%s</table>\n' "$html" \
      | sed -E 's|%PILL:([a-z0-9_-]+):([^%]*)%|<span class="pill \1">\2</span>|g'
  fi
  echo "</section>"
}

# Escape HTML for inline text values (used inside <pre> for journal previews).
htmlescape() {
  python3 -c 'import html,sys;sys.stdout.write(html.escape(sys.stdin.read()))'
}

# --- write output -------------------------------------------------------------

{
cat <<HEAD
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>kairos-triage-agent dashboard</title>
<style>
:root{
  --bg:#fafafa; --fg:#1c1c1c; --muted:#6b6b6b; --line:#e4e4e4;
  --panel:#fff; --accent:#0b5cad;
  --pill-ok:#d5e8d4; --pill-ok-fg:#245825;
  --pill-warn:#fff2cc; --pill-warn-fg:#7a5900;
  --pill-bad:#f8cecc; --pill-bad-fg:#6f1a1a;
  --pill-dry:#e6f0ff; --pill-dry-fg:#003366;
}
@media (prefers-color-scheme:dark){
  :root{ --bg:#111; --fg:#eaeaea; --muted:#9a9a9a; --line:#2b2b2b; --panel:#181818;
    --accent:#5aa8ff;
    --pill-ok:#1e3a1e; --pill-ok-fg:#a2d29e;
    --pill-warn:#3a2f0a; --pill-warn-fg:#e6c060;
    --pill-bad:#3a1414; --pill-bad-fg:#e69a94;
    --pill-dry:#0f2440; --pill-dry-fg:#8fb8ea; }
}
*{box-sizing:border-box}
body{background:var(--bg);color:var(--fg);font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
  margin:0;padding:24px 32px;max-width:1400px;margin:0 auto}
header{margin-bottom:20px}
h1{margin:0;font-size:22px}
.meta{color:var(--muted);font-size:12px;margin-top:4px}
h2{font-size:15px;margin:28px 0 10px;padding-bottom:6px;border-bottom:1px solid var(--line);letter-spacing:.02em;text-transform:uppercase;color:var(--muted)}
section{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:14px 18px;margin-bottom:16px}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{padding:6px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}
th{background:transparent;color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.03em}
tr:last-child td{border-bottom:none}
tbody tr:hover{background:rgba(127,127,127,.06)}
code,kbd,pre{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}
code{background:rgba(127,127,127,.12);padding:1px 5px;border-radius:3px}
pre{background:#0b0b0b;color:#e8e8e8;padding:12px 14px;border-radius:6px;overflow-x:auto;white-space:pre-wrap;line-height:1.4;margin:6px 0}
details{margin:8px 0;padding:6px 10px;border:1px solid var(--line);border-radius:6px;background:rgba(127,127,127,.04)}
details[open]{background:rgba(127,127,127,.06)}
summary{cursor:pointer;font-weight:600;font-size:13px}
summary .small{font-weight:400;color:var(--muted);margin-left:8px}
.pill{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;letter-spacing:.02em}
.pill.approve, .pill.done{background:var(--pill-ok);color:var(--pill-ok-fg)}
.pill.changes, .pill.awaiting-author, .pill.in-flight{background:var(--pill-warn);color:var(--pill-warn-fg)}
.pill.escalated, .pill.error{background:var(--pill-bad);color:var(--pill-bad-fg)}
.pill.dry, .pill.dry-run{background:var(--pill-dry);color:var(--pill-dry-fg)}
.stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin-top:6px}
.stat{background:rgba(127,127,127,.06);padding:12px 14px;border-radius:6px}
.stat .n{font-size:22px;font-weight:600;color:var(--accent)}
.stat .k{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}
.empty{color:var(--muted);font-style:italic;margin:6px 0 0}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
</style>
</head><body>

<header>
  <h1>kairos-triage-agent — dashboard</h1>
  <div class="meta">DB <code>$abs_db</code> — generated $now_utc</div>
</header>
HEAD

# ---- overview stats ---------------------------------------------------------
echo "<section><h2>Overview</h2><div class=stat-grid>"
sqlite3 "$DB" <<'SQL' | while IFS='|' read -r k v; do
SELECT 'slots',              (SELECT COUNT(*) FROM slots);
SELECT 'tickets touched',    (SELECT COUNT(*) FROM tickets);
SELECT 'approvals',          (SELECT COUNT(*) FROM verdicts WHERE verdict='approve');
SELECT 'changes requested',  (SELECT COUNT(*) FROM verdicts WHERE verdict='changes-requested');
SELECT 'escalations',        (SELECT COUNT(*) FROM slots WHERE outcome='escalated');
SELECT 'total tokens',       (SELECT COALESCE(SUM(tokens),0) FROM costs);
SELECT 'total usd',          printf('$%.2f',(SELECT COALESCE(SUM(usd),0.0) FROM costs));
SELECT 'gated calls',        (SELECT COUNT(*) FROM gated_calls);
SELECT 'artifacts',          (SELECT COUNT(*) FROM artifacts);
SELECT 'worker journals',    (SELECT COUNT(*) FROM worker_reports WHERE journal IS NOT NULL);
SQL
  printf '<div class="stat"><div class="n">%s</div><div class="k">%s</div></div>' "$v" "$k"
done
echo "</div></section>"

# ---- slots ------------------------------------------------------------------
section "Recent slots" "
SELECT
  substr(slot_id,1,17)                                        AS slot,
  ticket_ref                                                   AS ticket,
  CASE WHEN dry_run=1 THEN '%PILL:dry:dry-run%' ELSE 'live' END AS mode,
  '%PILL:'||outcome||':'||outcome||'%'                         AS outcome,
  entry_reason                                                 AS reason,
  gated_calls                                                  AS gated,
  envelope_writes                                              AS envwr,
  printf('%.1fs', wall_ms/1000.0)                              AS wall
FROM slots
ORDER BY started_at DESC
LIMIT 100"

# ---- tickets ----------------------------------------------------------------
section "Tickets touched" "
SELECT
  ticket_ref,
  kind,
  author,
  CASE WHEN third_party=1 THEN 'yes'
       WHEN third_party=0 THEN 'no'
       ELSE '—' END AS third_party,
  terminal_phase AS last_phase,
  first_seen_at,
  last_seen_at
FROM tickets
ORDER BY last_seen_at DESC"

# ---- verdicts ---------------------------------------------------------------
section "Reviewer verdicts" "
SELECT
  substr(v.slot_id,1,17)                                                     AS slot,
  v.ticket_ref                                                                AS ticket,
  v.round                                                                     AS round,
  '%PILL:'||replace(v.verdict,'changes-requested','changes')||':'||v.verdict||'%' AS verdict,
  v.comment_count                                                             AS comments,
  v.ts
FROM verdicts v
ORDER BY v.ts DESC"

# ---- costs per slot ---------------------------------------------------------
section "Cost per slot" "
SELECT
  substr(c.slot_id,1,17) AS slot,
  c.ticket_ref           AS ticket,
  c.role,
  c.tokens,
  printf('$%.4f', c.usd) AS usd,
  c.ts
FROM costs c
ORDER BY c.ts DESC
LIMIT 100"

# ---- artifacts --------------------------------------------------------------
section "Artifacts produced" "
SELECT
  substr(slot_id,1,17) AS slot,
  ticket_ref           AS ticket,
  kind,
  ref,
  ts
FROM artifacts
ORDER BY artifact_id DESC
LIMIT 200"

# ---- per-ticket detail (conclusion + comments + journal) --------------------
echo '<section><h2>By ticket</h2>'
sqlite3 -separator $'\x1f' "$DB" "
  SELECT t.ticket_ref,
         COALESCE(t.kind,''),
         COALESCE(t.author,''),
         CASE WHEN t.third_party=1 THEN 'third-party' ELSE 'fleet' END,
         COALESCE(t.terminal_phase,'')
  FROM tickets t
  ORDER BY t.last_seen_at DESC" \
  | while IFS=$'\x1f' read -r tref kind author party phase; do

      echo "<details open>"
      echo "<summary><code>${tref}</code> <span class=\"small\">${kind} / ${author} / ${party} / <span class=\"pill ${phase}\">${phase}</span></span></summary>"

      # Latest verdict paragraph — the reviewer's return_text is the human-readable conclusion.
      echo "<h3 style=\"font-size:13px;margin:12px 0 4px;color:var(--muted)\">Latest reviewer conclusion</h3>"
      rid="$(sqlite3 "$DB" "SELECT report_id FROM worker_reports WHERE ticket_ref='$tref' AND role='reviewer' ORDER BY report_id DESC LIMIT 1")"
      if [ -n "$rid" ]; then
        echo "<pre>"
        sqlite3 "$DB" "SELECT COALESCE(return_text,'(no return text)') FROM worker_reports WHERE report_id=$rid" | htmlescape
        echo "</pre>"
      else
        echo '<p class="empty">no reviewer report yet</p>'
      fi

      # Per-finding comments.
      echo "<h3 style=\"font-size:13px;margin:12px 0 4px;color:var(--muted)\">Comments</h3>"
      cmts="$(sqlite3 -html "$DB" "
        SELECT round AS r, role, COALESCE(file,'—') AS file, COALESCE(line,'') AS line,
               problem, COALESCE(suggestion,'') AS suggestion
        FROM comments WHERE ticket_ref='$tref' ORDER BY round, comment_id")"
      [ -n "$cmts" ] && echo "<table>$cmts</table>" || echo '<p class="empty">no comments on record</p>'

      # Full reviewer journal (collapsed by default; it's long).
      echo "<h3 style=\"font-size:13px;margin:12px 0 4px;color:var(--muted)\">Reviewer journal</h3>"
      if [ -n "$rid" ]; then
        jlen="$(sqlite3 "$DB" "SELECT COALESCE(LENGTH(journal),0) FROM worker_reports WHERE report_id=$rid")"
        if [ "$jlen" != "0" ]; then
          echo "<details><summary>show journal <span class=\"small\">(${jlen} bytes)</span></summary>"
          echo "<pre>"
          sqlite3 "$DB" "SELECT journal FROM worker_reports WHERE report_id=$rid" | htmlescape
          echo "</pre>"
          echo "</details>"
        else
          echo '<p class="empty">journal empty</p>'
        fi
      fi

      echo "</details>"
    done
echo '</section>'

# ---- per-slot detail (events + journals) -----------------------------------
echo '<section><h2>Slot detail</h2>'
sqlite3 -separator '|' "$DB" "SELECT slot_id, COALESCE(ticket_ref,''), COALESCE(outcome,''), started_at FROM slots ORDER BY started_at DESC LIMIT 50" \
  | while IFS='|' read -r sid tick outc started; do
      echo "<details>"
      echo "<summary><code>${sid}</code> — <code>${tick}</code> — <span class=\"pill ${outc}\">${outc}</span> <span class=\"small\">${started}</span></summary>"
      echo "<h3 style=\"font-size:13px;margin:10px 0 4px;color:var(--muted)\">Events</h3>"
      ev="$(sqlite3 -html "$DB" \
        "SELECT ts, COALESCE(phase_before,'—') AS 'phase before', COALESCE(phase_after,'—') AS 'phase after',
                COALESCE(role,'') AS role, action, COALESCE(tokens,'') AS tokens, COALESCE(note,'') AS note
         FROM events WHERE slot_id='$sid' ORDER BY event_id")"
      [ -n "$ev" ] && echo "<table>$ev</table>" || echo '<p class="empty">no events</p>'

      echo "<h3 style=\"font-size:13px;margin:14px 0 4px;color:var(--muted)\">Worker journals</h3>"
      # Each journal in its own <details>.
      sqlite3 -separator $'\x1f' "$DB" \
        "SELECT report_id, role, round, COALESCE(journal_path,''), COALESCE(LENGTH(journal),0)
         FROM worker_reports WHERE slot_id='$sid' ORDER BY report_id" \
        | while IFS=$'\x1f' read -r rid role round jpath jlen; do
            echo "<details><summary>$role — round $round <span class=small>($jlen bytes, <code>$jpath</code>)</span></summary>"
            if [ "$jlen" = "0" ]; then
              echo '<p class="empty">no journal written</p>'
            else
              echo "<pre>"
              sqlite3 "$DB" "SELECT COALESCE(journal,'') FROM worker_reports WHERE report_id=$rid" | htmlescape
              echo "</pre>"
            fi
            echo "</details>"
          done

      echo "<h3 style=\"font-size:13px;margin:14px 0 4px;color:var(--muted)\">Gated calls</h3>"
      gc="$(sqlite3 -html "$DB" "SELECT ts, command FROM gated_calls WHERE slot_id='$sid' ORDER BY gated_id")"
      [ -n "$gc" ] && echo "<table>$gc</table>" || echo '<p class="empty">none</p>'

      echo "</details>"
    done
echo '</section>'

cat <<'TAIL'
<footer style="margin-top:32px;color:var(--muted);font-size:12px">
  generated by <code>dashboard/generate.sh</code> — regenerate any time; no cache, no server.
</footer>
</body></html>
TAIL

} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
